# Generated by Django 6.0 on 2026-01-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicileapplication',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
