# Generated by Django 6.0 on 2026-03-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_domicileapplication_certificate_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='domicileapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domicileapplication',
            name='pan_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='domicileapplication',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='residence_years',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IncomeCertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('aadhaar', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('annual_income', models.CharField(max_length=20)),
                ('income_source', models.CharField(choices=[('agriculture', 'Agriculture'), ('business', 'Business'), ('salary', 'Salary / Service'), ('pension', 'Pension'), ('other', 'Other')], default='other', max_length=30)),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('certificate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('gu', 'Gujarati'), ('kn', 'Kannada')], default='en', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
