# Generated by Django 6.0 on 2026-03-26 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_domicileapplication_father_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domicileapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Domicile Application', 'verbose_name_plural': 'Domicile Applications'},
        ),
        migrations.AlterModelOptions(
            name='incomecertificateapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Income Certificate Application', 'verbose_name_plural': 'Income Certificate Applications'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='domicileapplication',
            name='review_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Review Notes / Rejection Reason'),
        ),
        migrations.AddField(
            model_name='domicileapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='incomecertificateapplication',
            name='review_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Review Notes / Rejection Reason'),
        ),
        migrations.AddField(
            model_name='incomecertificateapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=20, verbose_name='Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='address',
            field=models.TextField(verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificate Number'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='district',
            field=models.CharField(max_length=50, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's / Spouse's Name"),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='gender',
            field=models.CharField(default='', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='pan_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='purpose',
            field=models.CharField(max_length=50, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='residence_years',
            field=models.IntegerField(default=0, verbose_name='Years of Residence'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Under Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicile_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domicileapplication',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voter ID'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=20, verbose_name='Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='address',
            field=models.TextField(verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='annual_income',
            field=models.CharField(max_length=20, verbose_name='Annual Income (INR)'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificate Number'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='district',
            field=models.CharField(max_length=50, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's / Spouse's Name"),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='gender',
            field=models.CharField(default='', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='income_source',
            field=models.CharField(choices=[('agriculture', 'Agriculture / Farming'), ('business', 'Business / Self-Employed'), ('salary', 'Salary / Service'), ('pension', 'Pension'), ('other', 'Other')], default='other', max_length=30, verbose_name='Source of Income'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='pan_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='purpose',
            field=models.CharField(max_length=100, verbose_name='Purpose of Certificate'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Under Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='incomecertificateapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
